### PR TITLE
Update to support SDL 2.0.14

### PR DESCRIPTION
**Pull request by a-hurst**
Currently a work-in-progress, but all new relevant functions have been wrapped and corresponding tests have been added to the test suite (even if many of them are just empty).

Main hold-up now is some problems with some semi-random segfaults during CI which didn't seem to happen before. I'll look into it when I have a chance, hopefully within the next month.

### CODE REVIEW

**Comment by pvallet** [comment]
Hello Austin! Is this PR the last thing to be completed before releasing a new version?

**Comment by a-hurst** [comment]
@pvallet That's the plan! I actually don't have PyPi access for py-sdl2 (only @marcusva is able to do that), but once this is merged I think it makes sense to do a new release.

I've been deeply focused on another projects over the past few weeks, but that's coming to a close soon so I can hopefully sort out the phantom segfaults and get this merged.

**Comment by pvallet** [comment]
That sounds great! Good luck with wrapping up the other project and the weird segfaults ;)

**Comment by a-hurst** [comment]
CI seems stable now after transitioning to Github Actions, and I'm not able to reproduce the segfaults on real hardware, so I think this is good to merge now!

**Pull request merged**
