### PR TITLE
[wip] Re-enable pixelaccess tests for pypy

### PR DESCRIPTION
**Pull request by stillinbeta**

### CODE REVIEW

**Comment by a-hurst** [comment]
@stillinbeta I'd be happy to do this, but unfortunately an upstream PyPy update has broken some core functionality pysdl2 depends on (see #152). I'm looking into a fix, but if you have any ideas on how to get it working again please let me know!

**Comment by mattip** [comment]
PyPy dev here. I don't know what would be more work: redoing the _ctypes support in PyPy to allow editing structures at runtime, or converting py-sdl2 to cffi, which would have the additional advantage of being very performant on PyPy. In gh-152 there was some concern about cffi requiring a compiler. CFFI has two modes of operation: only one requires a compiler, the other works much like ctypes (at the cost of performance). As a side note, I will point out that most prominent python packages distribute a wheel on PyPI, which would totally solve the "needs a compiler" problem if you choose to go the performant route.  As a side-note to the side-note, you have only a [source tarball](https://pypi.org/project/PySDL2/#files). People who install via `pip install pysdl2` will be forced to
- download and unpack the source tarball
- run `setup.py bdist_wheel` to build a local wheel package
- cache that wheel for future use
- re-run `pip install <path-to-wheel>` to install the local wheel.

So you might want to consider [distributing wheels](https://github.com/joerick/cibuildwheel) to save the end-users extra work.

There is already [pysdl2-cffi](https://pypi.org/project/pysdl2-cffi/#files) which uses cffi, but the [open issues](https://bitbucket.org/dholth/pysdl2-cffi/issues?status=new&status=open) does not inspire confidence that the project is still active.

**Comment by mattip** [comment]
Also, as far a wheels go, there are thoughts about how to make CFFI support [limited API c-extensions](https://docs.python.org/3/c-api/stable.html?highlight=py_limited_api) for python 3 which would mean a single wheel per achitecture (windows, macOS, linux) and implementation (CPython, PyPy).

**Comment by a-hurst** [comment]
@mattip Thanks so much for the response! I actually think I figured out a PyPy-compliant fix: instead of creating opaque Structure objects for the opaque SDL2 types, I switched the classes in question over to being subclasses of c_void_p, which seems to avoid the _fields_ caching issue completely (since we don't actually need the fields for anything). 

With the fix, PyPy2 is now passing on Travis (though PyPy3 caught a segfault, hopefully that's random and not due to my patch): https://travis-ci.org/marcusva/py-sdl2/builds/637245861?utm_medium=notification&utm_source=github_status

**Pull request merged**
