### PR TITLE
Update testing suite and migrate to pytest

### PR DESCRIPTION
**Pull request by a-hurst**
Ported all the tests over to pytest from unittest, allowing for cleaner and more flexible testing.

Also:
* Expanded tests and fixed/suppressed warnings for various libraries
* Added MP3/opus support to the compiled SDL2 libraries on Linux CI
* Prevented the utterly haunted and somewhat useless TTF_SizeUNICODE from randomly failing (marked it as 'expected fail')
* Added caching for pip so PyPy tests don't take so long to run (since they otherwise have to compile numpy every time they run).

### CODE REVIEW

**Comment by marcusva** [comment]
I'm not really seeing the benefit from moving to pytest instead of keeping the unittest framework intact. pytest is compatible with unittest, however, someone wanting to run the tests without pytest installed will not be able to do so with this change.
Can you explain the tangible benefit for using pytest exclusively?

**Comment by a-hurst** [comment]
The main reason I wanted to switch over was that I was getting some really weird ctypes behaviour with unittest.TestCase and pytest (TTF_SizeUNICODE producing the expected size results when run in IPython or a Python script, but producing incorrect ones in pytest, with identical code), and moving over to pure pytest fixed the bizzare problem on my VM. However, as you can see from the CI history, that fixed the issue for some VMs and broke it for others, so I've just decided TTF_SizeUNICODE is cursed in Python and marked it as expected fail.

Apart from that, pytest helpfully allows for marking tests as expected fails (needed in various spots to deal with SDL2 binary bugs that differ between architectures, OSes, and binary versions, e.g. XCF loading), and allows for (I think) much cleaner writing of tests using `assert (expression)` instead of `self.assertSomeSpecificThing(a, b)` syntax and allowing tests outside of TestCase classes.

**Comment by a-hurst** [comment]
@marcusva unless you have any other objections, or feel strongly that this isn't justified, I'm going to merge this tomorrow evening. I've been holding off writing/updating unit tests for various fixes until this either gets merged or shot down, so once its fate is decided I can address that backlog and know what format to write tests in going forward.

**Comment by marcusva** [comment]
Go ahead, the arguments sound good enough to me to switch to pytest entirely.
Thanks for the hard work on this one!

**Pull request merged**
